- name: Save image version into /etc/esdc.version
  copy: content="{{ appliance_version | default('v' + image_version) }}" dest="/etc/esdc.version" mode=0644 owner=root group=root
  when: release_type == "stable"
