- name: Generate self-signed SSL certificate
  command: openssl req -new -nodes -x509 -subj '/CN=*.*/O=Danube Cloud/' -days 10000 -keyout /etc/pki/tls/certs/server.pem -out /etc/pki/tls/certs/server.pem -extensions v3_ca creates=/etc/pki/tls/certs/server.pem

- name: Change permissions of /etc/pki/tls/certs/server.pem
  file: path=/etc/pki/tls/certs/server.pem owner=root group=root mode=0600

- name: Configure openssl.cnf for generating erigonesd SSL certificate
  ini_file: dest="/etc/pki/tls/openssl.cnf"
            section="SAN"
            option="subjectAltName"
            value="{{ esdc_mgmt.erigonesd.subjectAltName }}"

- name: Generate new temporary erigonesd SSL key and certificate for haproxy to work
  command: openssl req -x509 -sha256 -nodes -days 10000 -subj '/CN=esdc.local/O=Danube Cloud/' -reqexts SAN -extensions SAN -newkey rsa:8192 -keyout "{{ esdc_mgmt.erigonesd.ssl_file }}" -out "{{ esdc_mgmt.erigonesd.ssl_file }}" creates="{{ esdc_mgmt.erigonesd.ssl_file }}"

- name: Change permissions of {{ esdc_mgmt.erigonesd.ssl_file }}
  file: path="{{ esdc_mgmt.erigonesd.ssl_file }}" owner=root group=root mode=0600
