---
- fail: msg="Invalid OS; Only CentOS 7 is supported."
  when: ansible_distribution != "CentOS" or ansible_distribution_major_version != "7"

- name: Install python-pip
  yum: name=python-pip state=present

- name: Create Ludolph service group
  group: name=ludolph
         state=present

- name: Create Ludolph service user
  user: name=ludolph
        group=ludolph
        home=/var/lib/ludolph
        shell=/sbin/nologin

- name: Install Ludolph
  pip: name=ludolph state=latest

- name: Create Ludolph configuration file
  template: src=ludolph.cfg.j2
            dest=/etc/ludolph.cfg
            owner=root
            group=ludolph
            mode=0640

- name: Create Ludolph startup script
  template: src=ludolph.service.j2
            dest=/etc/systemd/system/ludolph.service
            owner=root
            group=root
            mode=0644

- name: Ensure Ludolph is running
  service: name=ludolph state=started enabled=yes
  when: ludolph_service_enabled
