---
- name: Install LeoFS packages
  command: pkgin install -y leofs_storage leofs_gateway leofs_manager

- name: Copy LeoFS initialization script
  copy: src=35-leofs.sh
      dest=/var/zoneinit/includes/35-leofs.sh
      owner=root
      group=root
      mode=0755
