---
- name: Include OS-specific variables
  include_vars: ../defaults/{{ ansible_distribution }}.yml

- name: Set up nginx repositories (CentOS 6)
  yum: name={{ nginx_repo_el6 }} state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Set up nginx repositories (CentOS 7)
  yum: name={{ nginx_repo_el7 }} state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Install nginx packages (SmartOS)
  command: pkgin -y install {{ item }}
  register: res
  changed_when: "'nothing to do.' not in res.stdout"
  with_items: "{{ nginx_packages }}"
  when: ansible_distribution == "SmartOS"

- name: Install nginx packages (CentOS)
  yum: name={{ item }} state=present
  with_items: "{{ nginx_packages }}"
  when: ansible_distribution == "CentOS"

- name: Create nginx configuration file
  template: src=nginx.conf.j2
            dest={{ nginx_config_dir }}/nginx.conf
            owner=root
            group=root
            mode=0644
            validate="nginx -t -c %s"
  notify: restart nginx

- name: Create vhosts.d directory
  file: path={{ nginx_config_dir }}/vhosts.d
        owner=root
        group=root
        mode=0755
        state=directory

- name: Start nginx and enable at boot (CentOS)
  service: name={{ nginx_service }} enabled=yes state=started
  when: ansible_distribution == "CentOS"

- name: Start nginx and enable at boot (SmartOS)
  shell: svcadm enable {{ nginx_service }}
  when: ansible_distribution == "SmartOS"
