---
- name: Include OS-specific variables
  include_vars: ../defaults/{{ ansible_distribution }}.yml

- name: Install Zabbix repository package (CentOS)
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm state=present
  when: ansible_distribution == "CentOS"

- name: Install Zabbix agent (CentOS)
  yum: name={{ item }} state=latest
  with_items:
    - zabbix-agent
  when: ansible_distribution == "CentOS"

- name: Copy Zabbix agent package
  copy: src={{ zabbix_agent_package }}
        dest=/tmp/{{ zabbix_agent_package }}
        mode=0644
        owner=root
        group=root
  when: ansible_distribution == "SmartOS"

  # pkg_add will ask if we want to install unsigned package.
  # We disable signature verification just for the package installation.
  # TODO: sign our pkgsrc packages
- name: Bypass package signing prompt
  shell: echo "VERIFIED_INSTALLATION=never" > /tmp/pkg_install_noverify.conf
  when: ansible_distribution == "SmartOS"

- name: Install Zabbix agent (SmartOS)
  command: pkg_add -f -C /tmp/pkg_install_noverify.conf /tmp/{{ zabbix_agent_package }}
  when: ansible_distribution == "SmartOS"

- name: Create Zabbix agent configuration file
  template: src=zabbix_agentd.conf.j2
            dest={{ zabbix_agent_config_dir }}/zabbix_agentd.conf
            owner=root
            group=root
            mode=0644
  notify: restart zabbix-agent

- name: Place zabbix zoneinit script (SmartOS)
  copy: src=21-zabbix.sh
        dest=/var/zoneinit/includes/21-zabbix.sh
        mode=0755
        owner=root
        group=root
  when: ansible_distribution == "SmartOS"

- name: Disable Zabbix agent service (SmartOS)
  service: name=zabbix-agent state=stopped enabled=no
  when: ansible_distribution == "SmartOS"

- name: Ensure Zabbix agent is running and enabled
  service: name=zabbix-agent state=started enabled=yes
  when: ansible_distribution == "CentOS"
